### ISSUE TITLE
other dataset

### ISSUE THREAD

**Issue by un-lock-me** [tshi04/SeaNMF#2]
hi,
I have a question about your code, hope you reply.
I was wondering how can I apply this model to another dataset?
It seems it the input data here has been prepared already and then pass to this model

**Comment by tshi04** [comment]
1. Please prepare two files: the document term matrix and vocabulary. For the format, please go to the data to check the two files.
2. go to train.py. Change corpus_file and vocab_file to the location of your files. Or you can use the arguments. 

Let me know if you still have problems.

**Comment by un-lock-me** [comment]
Well, I had difficulty applying my data on your code, do you mind to share the method in which convert your data to doc term matrix, so it will be easier to work with your code.
thanks:)

**Comment by tshi04** [comment]
Hi Saria,

I will update the codes this week and add the data processing codes. Please check the updated version later this week.

**Comment by un-lock-me** [comment]
Thanks,
I'm looking to see your update and apply that on a very large dataset.

Thanks for replying back :)

**Comment by npfah38** [comment]
Would just like to mention that I am also interested in trying out this code for topic modeling, following along the conversation on how to create the doc-term matrix and vocabulary...

**Comment by tshi04** [comment]
I updated the codes last night. Let me know if you need anything else.
