### ISSUE TITLE
How to assign topics to new sentences using a trained model ? 

### ISSUE THREAD

**Issue by kaislar** [tshi04/SeaNMF#4]
Hello, 
I just trained the model on my data and got the W matrix. I would like to assign each sentence of my dataset to a topic, how can i do that using your code? 
Thanks

**Comment by tshi04** [comment]
The W matrix is used to find topics and H matrix is related to the document or the sentence. So I think one way is to use H matrix as the weight to assign a sentence to a topic. In the paper, we use H matrix for the classification task.

**Comment by kaislar** [comment]
Thank you for you answer, If someone else need it. 
I got the topic assigned to the sentence by the argmax on H matrix. 

`results['topic']= numpyp.argmax(H,axis=1)`

**Comment by tshi04** [comment]
Thanks :-)
