### ISSUE TITLE
Topic inference on new/unseen corpus/data

### ISSUE THREAD

**Issue by bauer-jan** [tshi04/SeaNMF#5]
First of all, thanks for your work! 

Do you know how we can assign topics to new data which we did not use for the initial training of the model? You described in another question (https://github.com/tshi04/SeaNMF/issues/4) how to use the H matrix for getting the most probable topics for every text in the training corpus: 

`numpy.argmax(H,axis=1)`

Is there a way to infer new data with the trained model without retraining the model? I assume i need to use W and Wc, only using W for the calculation would not be sufficient to work with word embeddings.
All the best :)

**Comment by tshi04** [comment]
Hi Hahny, for an unseen document, my suggestion is to make use of W to optimize H only.

**Comment by bauer-jan** [comment]
Thanks for your response! I used W (addition of the vectors for every word occuring from a tweet in the matrix) to calculate the topic for it. If i do this with the documents seaNMF was trained on there are differences beween the topic for a document assigned in H as i would calcualte the topic only with W. Do you have a guidance on how to address this issue or is this the vagueness for "new" data.
